### ISSUE TITLE
Что

### ISSUE THREAD

**Issue by blessed-988** [dsawfer/Calc#1]
Что вершит судьбу человечества в этом мире? Некое незримое существо или закон, подобно Длани Господней парящей над миром? По крайне мере истинно то, что человек не властен даже над своей волей.

**Comment by dsawfer** [comment]
Tell me what, tell me what, tell me what you want
I don't know why, don't know why, don't know why you afraid
Tell me what, tell me what, tell me what you say
I don't know why, don't know why, too late, it's too late
